name: GPT Doc Automation

on:
  push:
    # Run on any push to any branch. Adjust as needed.
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  gpt-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          # We need to fetch the full history so we can compare HEAD~1, etc.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Pin the openai library to 0.28.0 for older-style ChatCompletion usage
          pip install openai==0.28.0

      - name: Determine changed files
        id: changes
        run: |
          # Compare HEAD to the previous commit in this branch
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "CHANGED_FILES=$CHANGED_FILES"
          # Write to $GITHUB_ENV so other steps can read it
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run GPT doc updater
        run: |
          python scripts/doc_updater.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHANGED_FILES: ${{ env.CHANGED_FILES }}

      - name: Commit doc updates
        run: |
          # If any docs were generated/updated, commit them
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs
            git commit -m "chore: Update docs via GPT"
          else
            echo "No documentation changes."
          fi

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Typically the base is 'main' or whatever your primary branch is
          base: main
          # The "head" is the same branch that triggered the workflow
          branch: ${{ github.ref_name }}
          title: "GPT-Docs: Automated Documentation Updates"
          body: "Documentation changes generated by GPT."
          # If a PR already exists from this branch, update it
          update-existing-pr: true
